# Generated by Django 4.2.6 on 2023-10-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "sno",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("mobile", models.BigIntegerField()),
                ("education", models.CharField(max_length=80)),
                ("stream", models.CharField(max_length=80, null=True)),
                ("college", models.CharField(max_length=80, null=True)),
                ("gender", models.CharField(max_length=20)),
                ("pass_year", models.IntegerField()),
                ("course", models.CharField(max_length=80)),
                ("b_type", models.CharField(max_length=80)),
                ("reff", models.CharField(max_length=200)),
                ("remark", models.CharField(max_length=255)),
            ],
        ),
    ]
